name: Build, Test & Dockerize

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
  sudo apt-get update
  sudo apt-get install -y nlohmann-json3-dev

      - name: Compile & run unit tests
        run: |
          g++ -std=c++17 -IStockAI -IStockAI/include StockAI/main.cpp 
StockAI/test.cpp -o test.out
          ./test.out

      - name: Build Docker image
        run: docker build -t stockai .

